name: paginate_firestore
description: A flutter package to simplify pagination with firestore data.
version: 1.0.3+1
homepage: https://github.com/excogitatr/paginate_firestore
issue_tracker: https://github.com/excogitatr/paginate_firestore/issues

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # bloc: ^8.0.3
  bloc: ^8.1.2
  # flutter_bloc: ^8.0.1
  flutter_bloc: ^8.1.3
  # cloud_firestore: ^4.5.3
  cloud_firestore: ^5.0.1
  # provider: ^6.0.2
  provider: ^6.0.5
 

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
